export const REDIRECTION_ENDPOINT = 'http://e3r10p16.1337.ma:3001/profile/dfghjk'
export const PROTOCOL = 'htpp://'
export const SEPARATOR = ':'
export const VALIDATION_EMAIL_ENDPOINT = '/api/v1/auth/verified/'
export const REDIRECTION_ENDPOINT_VALID_EMAIL = 'http://e3r10p16.1337.ma:3001/login'