export const JWT_EMAIL_SECRET = 'JWT_EMAIL_SECRET'
export const JWT_SECRET = 'JWT_SECRET'
export const USERNAME_DB = 'user_name'
export const TOKEN_EMAIL_EXPIRATION_TIME = 'TOKEN_EMAIL_EXPIRATION_TIME'
export const EMAIL_SUBJECT = 'EMAIL_SUBJECT'
export const PORT = 'PORT'
